theme: jekyll-theme-minimal
title: Harrison's Homepage
description: "Practiced training mentor and manager. Experienced cloud engineer, technical trainer, instructional designer, and curriculum architect (10 years). Certified in technical instruction and cloud technologies."