theme: jekyll-theme-minimal
title: Harrison Sherwin
description: "Practiced training mentor and manager. Experienced cloud engineer, technical trainer, instructional designer, and curriculum architect (11 years). Certified in technical instruction and cloud technologies."

github_username: hasherwi
